### ISSUE TITLE
JSON support?

### ISSUE THREAD

**Issue by thoughtpunch** [wild5r/activeadmin_hstore_editor#9]
Seems like this could support the Postgres JSON column type as well. Any idea what would go into supporting this?

**Comment by anwajler** [comment]
I use it to **display** JSON fields.

**Comment by houen** [comment]
I just now implemented JSON, but with a string-backed db field. For that I just had to remove the `hstore_editor` call on the form level. Adding support for PG JSON type should be simple as well, since Rails will automatically convert the string to a JSON hash (if not, simply use JSON.parse in your model before_validation). After conversion to a Ruby Hash, Rails should take care of the saving as usual

**Comment by houen** [comment]
Also, thx for this great gem thoughtpunch!

**Comment by wild5r** [comment]
@houen thx for usage
